=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/catalogo_libros/catalogo_libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="libros">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="catalogo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="libro" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="titulo" type="xs:string"/>
                    <xs:element name="autor" type="xs:string"/>
                    <xs:element name="año" type="xs:integer"/> <xs:element name="genero" type="xs:string"/>
                    <xs:element name="descripcion" type="xs:string"/>
                    
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/catalogo_libros/catalogo_libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="libros.css" type="text/css"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogo_libros.xsd">
    <catalogo>
        <libro>
            <titulo>1984</titulo>
            <autor>George Orwell</autor>
            <año>1949</año>
            <genero>Distopía</genero>
            <descripcion>Una novela sobre la vigilancia estatal y el totalitarismo.</descripcion>
        </libro>
        
        <libro>
            <titulo>El Señor de los Anillos</titulo>
            <autor>J.R.R. Tolkien</autor>
            <año>1954</año>
            <genero>Fantasía</genero>
            <descripcion>La épica lucha por destruir el Anillo Único en la Tierra Media.</descripcion>
        </libro>

        <libro>
            <titulo>Un mundo feliz</titulo>
            <autor>Aldous Huxley</autor>
            <año>1932</año>
            <genero>Distopía</genero>
            <descripcion>Una sociedad gestionada mediante la genética y el condicionamiento.</descripcion>
        </libro>
    </catalogo>
</libros>
