=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/dni/dni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dni">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" minOccurs="1" maxOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name="nombre" />
                            <xs:element name="apellidos" />
                            <xs:element name="numero_nif"/>
                            <xs:element name="nacionalidad" />
                            
                            <xs:choice minOccurs="0">
                                <xs:element name="fecha_nacimiento" />    
                                <xs:element name="edad" />
                            </xs:choice>

                            <xs:element name="sexo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Hombre"/>
                                        <xs:enumeration value="Mujer"/>
                                    </xs:restriction>
                                </xs:simpleType>  
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/dni/dni.xml
<?xml version="1.0" encoding="UTF-8"?>
<dni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dni.xsd">
    
    <persona>
        <nombre>Juan</nombre>
        <apellidos>García Pérez</apellidos>
        <numero_nif>12345678Z</numero_nif>
        <nacionalidad>Española</nacionalidad>
        <fecha_nacimiento>1990-05-20</fecha_nacimiento>
        <sexo>Hombre</sexo>
    </persona>

    <persona>
        <nombre>María</nombre>
        <apellidos>López Iturbide</apellidos>
        <numero_nif>87654321X</numero_nif>
        <nacionalidad>Española</nacionalidad>
        <edad>25</edad>
        <sexo>Mujer</sexo>
    </persona>

</dni>
