=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/menu_restaurante/menu_restaurante.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plato" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="precio" type="xs:decimal"/>

                            <xs:element name="primero">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="macarrones"/>
                                        <xs:enumeration value="filete"/>
                                        <xs:enumeration value="platano"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="segundo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="patata"/>
                                        <xs:enumeration value="pera"/>
                                        <xs:enumeration value="kiwi"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/menu_restaurante/menu_restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="menu_restaurante.xsd">
    <plato>
        <nombre>Combinado 1</nombre>
        <precio>12.50</precio>
        <primero>macarrones</primero>
        <segundo>patata</segundo>    
    </plato>

    <plato>
        <nombre>Combinado Especial</nombre>
        <precio>15.00</precio>
        <primero>filete</primero>
        <segundo>pera</segundo>
    </plato>
</menu>
