=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/tarjeta_credito/tarjeta_credito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="banco">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tarjeta" minOccurs="1" maxOccurs="5">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="titular" />
                            <xs:element ref="numero_tarjeta" />
                            
                            <xs:element name="marca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="visa"/>
                                        <xs:enumeration value="mastercard"/>
                                        <xs:enumeration value="american express"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="caducidad" />

                            <xs:choice>
                                <xs:element name="limite_credito" />    
                                <xs:element name="saldo_disponible" />
                            </xs:choice>

                            <xs:element name="cvv" />

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="numero_tarjeta" type="xs:string"/>
</xs:schema>

=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/tarjeta_credito/tarjeta_credito.xml
<?xml version="1.0" encoding="UTF-8"?>
<banco xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:noNamespaceSchemaLocation="tarjeta_credito.xsd">
    
    <tarjeta>
        <titular>JUAN PEREZ</titular>
        <numero_tarjeta>4548 1234 5678 9101</numero_tarjeta>
        <marca>visa</marca>
        <caducidad>12/28</caducidad>
        <limite_credito>3000</limite_credito>
        <cvv>123</cvv>
    </tarjeta>

    <tarjeta>
        <titular>MARIA LOPEZ</titular>
        <numero_tarjeta>5412 8888 9999 0000</numero_tarjeta>
        <marca>mastercard</marca>
        <caducidad>05/27</caducidad>
        <saldo_disponible>1250.50</saldo_disponible>
        <cvv>456</cvv>
    </tarjeta>

</banco>
