=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/agenda_contactos/agenda_contactos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="agenda">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contacto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="apellido" type="xs:string"/>
              <xs:element name="telefono" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="categoria" type="xs:string"/>
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FerranCC5/Lenguajes2025-Ferran_Cutillas_Castillo/t2/XML/ejercicios_xml/agenda_contactos/agenda_contactos.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="agenda_contactos.xsd">
    <contacto>
        <nombre>Juan</nombre>
        <apellido>Pérez</apellido>
        <telefono>+34 600111222</telefono>
        <email>juan.perez@email.com</email>
        <categoria>Trabajo</categoria>
    </contacto>

    <contacto>
        <nombre>María</nombre>
        <apellido>García</apellido>
        <telefono>912345678</telefono>
        <email>m.garcia@email.com</email>
        <categoria>Familia</categoria>
    </contacto>

</agenda>
